#!/usr/bin/env python3
"""Calibrate the text and visual score thresholds."""
from __future__ import annotations
import argparse
import json
import pickle
from pathlib import Path
from huggingface_hub import snapshot_download
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve
from tqdm import tqdm
from datasets import load_dataset, Image, concatenate_datasets
from utils import load_model, extract_llama_hidden_solo, extract_clip_hidden
import sys
from sklearn.covariance import LedoitWolf
from sklearn.decomposition import PCA
from scipy.spatial.distance import mahalanobis
import torch
torch.backends.cudnn.enabled = False
torch.backends.cudnn.benchmark = False
LLAMA_LAYER = 17
CLIP_LAYER = 21

def apply_projector(X: np.ndarray, Q: np.ndarray | None) -> np.ndarray:
    if Q is None:
        return X
    return X - X @ Q @ Q.T

def calibrate_threshold(name: str, scores_unsafe: np.ndarray, scores_safe: np.ndarray) -> tuple[float, float]:
    scores = np.concatenate([scores_unsafe, scores_safe])
    labels = np.concatenate([np.ones(len(scores_unsafe)), np.zeros(len(scores_safe))])
    auc = roc_auc_score(labels, scores)
    fpr, tpr, thresholds = roc_curve(labels, scores)
    J = tpr - fpr
    idx = np.argmax(J)
    tau = float(thresholds[idx])
    print(f'\n  Calibration tau_{name}:')
    print(f'    AUC = {auc:.4f}   tau_{name} = {tau:.4f}')
    print(f'    TPR = {tpr[idx]:.1%}   FPR = {fpr[idx]:.1%}')
    return (tau, float(auc))

def split_by_label(n_total: int, labels: np.ndarray, n_cal: int, seed: int=42) -> dict:
    rng = np.random.default_rng(seed=seed)
    idx_unsafe = np.where(labels == 1)[0]
    idx_safe = np.where(labels == 0)[0]
    rng.shuffle(idx_unsafe)
    rng.shuffle(idx_safe)
    return {'unsafe_cal': idx_unsafe[:n_cal].tolist(), 'unsafe_test': idx_unsafe[n_cal:n_cal * 2].tolist(), 'safe_cal': idx_safe[:n_cal].tolist(), 'safe_test': idx_safe[n_cal:n_cal * 2].tolist()}

def load_harmful_splits_for_calibration(harmful_splits_path, out_dir, harmful_ds, harmful_labels, n_cal):
    p = Path(harmful_splits_path)
    if p.exists():
        splits = json.load(open(p))
        print(f'  [splits] Loaded from {p.name}')
        max_idx = max(max(splits['unsafe_cal']), max(splits['safe_cal']))
        assert max_idx < len(harmful_ds), f'Index {max_idx} outside the dataset range ({len(harmful_ds)} sample). Did the dataset change? Regenerate {p.name} with rebuild_dataset.py'
        print(f"  [splits] unsafe_cal={len(splits['unsafe_cal'])}  safe_cal={len(splits['safe_cal'])}")
        print(f"  [splits] unsafe_test={len(splits['unsafe_test'])}  (reserved, not used here)")
        local_copy = out_dir / 'eval_splits_harmfulcontents.json'
        if not local_copy.exists():
            json.dump(splits, open(local_copy, 'w'), indent=2)
        return splits
    print(f'\n  [WARN] {p} not found.')
    print(f'  [WARN] Run rebuild_dataset.py --harmful_splits {p} FIRST')
    print(f'  [WARN] of calibrate_tau_tv.py to guarantee leakage-free evaluation.')
    print(f'  [WARN] Generating local splits that may overlap with training...\n')
    import numpy as np
    rng = np.random.default_rng(seed=42)
    idx_unsafe = np.where(harmful_labels == 1)[0]
    idx_safe = np.where(harmful_labels == 0)[0]
    rng.shuffle(idx_unsafe)
    rng.shuffle(idx_safe)
    splits = {'seed': 42, 'n_cal': n_cal, 'unsafe_cal': [int(i) for i in idx_unsafe[:n_cal]], 'unsafe_test': [int(i) for i in idx_unsafe[n_cal:n_cal * 2]], 'safe_cal': [int(i) for i in idx_safe[:n_cal]], 'safe_test': [int(i) for i in idx_safe[n_cal:n_cal * 2]], 'unsafe_train_pool': [int(i) for i in idx_unsafe[n_cal * 2:]], 'safe_train_pool': [int(i) for i in idx_safe[n_cal * 2:]], '_warning': 'Generated by calibrate_tau_tv without rebuilding — possible leakage'}
    local_copy = out_dir / 'eval_splits_harmfulcontents.json'
    json.dump(splits, open(local_copy, 'w'), indent=2)
    return splits

def extract_st_toxicchat(dataset, indices, model, processor, clf_text, ortho_Q_text) -> np.ndarray:
    scores = []
    for i, idx in enumerate(tqdm(indices, desc='  toxic-chat S_T')):
        row = dataset[idx]
        text = row.get('user_input', '')
        try:
            h = extract_llama_hidden_solo(text, model, processor, LLAMA_LAYER)
            hr = h.reshape(1, -1)
            if ortho_Q_text is not None:
                hr = apply_projector(hr, ortho_Q_text)
            s = float(clf_text.predict_proba(hr)[0, 1])
        except Exception as e:
            print(f'  [warn] toxic-chat idx={idx}: {e}')
            s = 0.0
        scores.append(s)
    return np.array(scores)

def extract_sv_harmful(dataset, indices, model, processor, clf_visual, ortho_Q_visual) -> np.ndarray:
    scores = []
    for idx in tqdm(indices, desc='  harmful-contents S_V'):
        row = dataset[idx]
        try:
            image = row['image_path'].convert('RGB')
            h = extract_clip_hidden(image, model, processor, CLIP_LAYER)
            hr = h.reshape(1, -1)
            if ortho_Q_visual is not None:
                hr = apply_projector(hr, ortho_Q_visual)
            s = float(clf_visual.predict_proba(hr)[0, 1])
        except Exception as e:
            print(f'  [warn] harmful idx={idx}: {e}')
            s = 0.0
        scores.append(s)
    return np.array(scores)

def extract_sv_mmstar(dataset, indices, model, processor, clf_visual, ortho_Q_visual) -> np.ndarray:
    scores = []
    for idx in tqdm(indices, desc='  MMStar_cal S_V'):
        row = dataset[idx]
        try:
            image = row['image'].convert('RGB')
            h = extract_clip_hidden(image, model, processor, CLIP_LAYER)
            hr = h.reshape(1, -1)
            if ortho_Q_visual is not None:
                hr = apply_projector(hr, ortho_Q_visual)
            s = float(clf_visual.predict_proba(hr)[0, 1])
        except Exception as e:
            print(f'  [warn] mmstar idx={idx}: {e}')
            s = 0.0
        scores.append(s)
    return np.array(scores)

def run(args):
    probes_dir = Path(args.probes)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    print('\n[1] Loading probe_text / probe_visual...')
    with open(probes_dir / 'probe_text.pkl', 'rb') as f:
        obj_text = pickle.load(f)
    if isinstance(obj_text, dict):
        clf_text, ortho_Q_text = (obj_text['clf'], obj_text.get('ortho_Q'))
    else:
        clf_text, ortho_Q_text = (obj_text, None)
    with open(probes_dir / 'probe_visual_orthogonalized.pkl', 'rb') as f:
        obj_visual = pickle.load(f)
    if isinstance(obj_visual, dict):
        clf_visual, ortho_Q_visual = (obj_visual['clf'], obj_visual.get('ortho_Q'))
    else:
        clf_visual, ortho_Q_visual = (obj_visual, None)
    visual_path = probes_dir / 'probe_visual_orthogonalized.pkl'
    with open(visual_path, 'rb') as f:
        obj_visual = pickle.load(f)
    if isinstance(obj_visual, dict):
        ortho_Q_visual = obj_visual.get('ortho_Q')
    else:
        ortho_Q_visual = None
    print(f'  ortho_Q_text available:   {ortho_Q_text is not None}')
    print(f'  ortho_Q_visual available: {ortho_Q_visual is not None}')
    print('\n[2] Loading dataset...')
    toxicchat_ds = load_dataset('lmsys/toxic-chat', 'toxicchat0124', split='test')
    print(f'  toxic-chat: {len(toxicchat_ds)} sample')
    print(f'  [check] example: {toxicchat_ds[0]}')
    repo_path = snapshot_download(repo_id='onullusoy/harmful-contents', repo_type='dataset', allow_patterns=['csv/train.csv', 'data/test/*'])
    repo_path = Path(snapshot_download(repo_id='onullusoy/harmful-contents', repo_type='dataset', allow_patterns=['csv/train.csv', 'csv/test.csv', 'data/train/*', 'data/test/*']))
    data_files = {'train': str(repo_path / 'csv' / 'train.csv'), 'test': str(repo_path / 'csv' / 'test.csv')}
    ds_dict = load_dataset('csv', data_files=data_files)
    n_train = len(ds_dict['train'])
    harmful_ds = concatenate_datasets([ds_dict['train'], ds_dict['test']])

    def add_path(example, idx):
        folder = 'train' if idx < n_train else 'test'
        return {'image_path': str(repo_path / 'data' / folder / example['name'])}
    harmful_ds = harmful_ds.map(add_path, with_indices=True)
    harmful_ds = harmful_ds.cast_column('image_path', Image())
    HARM_COLUMNS = ['drugs', 'weapons', 'gambling', 'nudity', 'sexy', 'smoking', 'violence']
    harmful_labels = np.array([1 if any((row[c] == 1 for c in HARM_COLUMNS)) else 0 for row in harmful_ds])
    print('\n[3] Managing splits...')
    splits_path_t = out_dir / 'eval_splits_toxicchat.json'
    splits_v = load_harmful_splits_for_calibration(args.harmful_splits, out_dir, harmful_ds, harmful_labels, args.n_cal)
    toxicchat_labels = np.array(toxicchat_ds['toxicity'])
    if splits_path_t.exists():
        splits_t = json.load(open(splits_path_t))
    else:
        splits_t = split_by_label(len(toxicchat_ds), toxicchat_labels, args.n_cal)
        json.dump(splits_t, open(splits_path_t, 'w'), indent=2)
        print(f'  [splits] Saved in {splits_path_t}')
    print(f'row keys: {list(harmful_ds[0].keys())}')
    print('\n[4] Loading LLaVA...')
    model, processor = load_model(gpu=args.gpu)
    print('\n[5] Extraction S_T on toxic-chat_cal...')
    cache_t = out_dir / f'st_cal_seed42_n{args.n_cal}.pkl'
    if cache_t.exists() and (not args.recompute):
        cached = pickle.load(open(cache_t, 'rb'))
        st_unsafe, st_safe = (cached['unsafe'], cached['safe'])
    else:
        st_unsafe = extract_st_toxicchat(toxicchat_ds, splits_t['unsafe_cal'], model, processor, clf_text, ortho_Q_text)
        st_safe = extract_st_toxicchat(toxicchat_ds, splits_t['safe_cal'], model, processor, clf_text, ortho_Q_text)
        print(f'st_unsafe: {st_unsafe.mean()}, st_safe: {st_safe.mean()}')
        pickle.dump({'unsafe': st_unsafe, 'safe': st_safe}, open(cache_t, 'wb'))
    print('\n[5b] Extraction S_V on HarmfulContents_cal...')
    cache_v = out_dir / f'sv_cal_seed42_n{args.n_cal}.pkl'
    if cache_v.exists() and (not args.recompute):
        cached = pickle.load(open(cache_v, 'rb'))
        sv_unsafe, sv_safe = (cached['unsafe'], cached['safe'])
        print(f'sv_unsafe: {sv_unsafe.mean()}, sv_safe: {sv_safe.mean()}')
    else:
        sv_unsafe = extract_sv_harmful(harmful_ds, splits_v['unsafe_cal'], model, processor, clf_visual, ortho_Q_visual)
        sv_safe = extract_sv_harmful(harmful_ds, splits_v['safe_cal'], model, processor, clf_visual, ortho_Q_visual)
        print(f'sv_unsafe: {sv_unsafe.mean()}, sv_safe: {sv_safe.mean()}')
        pickle.dump({'unsafe': sv_unsafe, 'safe': sv_safe}, open(cache_v, 'wb'))
    mmstar_cal_path = out_dir / 'eval_splits.json'
    if not mmstar_cal_path.exists():
        mmstar_cal_path = out_dir / 'eval_splits_v13.json'
    if mmstar_cal_path.exists():
        mmstar_splits = json.load(open(mmstar_cal_path))
        mmstar_ds = load_dataset('Lin-Chen/MMStar', split='val')
        cache_mmstar = out_dir / f"sv_mmstar_cal_n{len(mmstar_splits['mmstar_cal'])}.pkl"
        if cache_mmstar.exists() and (not args.recompute):
            sv_safe_mmstar = pickle.load(open(cache_mmstar, 'rb'))
        else:
            sv_safe_mmstar = extract_sv_mmstar(mmstar_ds, mmstar_splits['mmstar_cal'], model, processor, clf_visual, ortho_Q_visual)
            pickle.dump(sv_safe_mmstar, open(cache_mmstar, 'wb'))
        sv_safe = np.concatenate([sv_safe, sv_safe_mmstar])
        print(f'  [mmstar] added {len(sv_safe_mmstar)} safe controls from MMStar_cal, sv_safe total={len(sv_safe)}')
    else:
        print(f'  [warn] {mmstar_cal_path} not found; skipping MMStar in calibration tau_V')
    print('\n[6] Calibration thresholds...')
    tau_T, auc_T = calibrate_threshold('T', st_unsafe, st_safe)
    tau_V, auc_V = calibrate_threshold('V', sv_unsafe, sv_safe)
    cfg_path = out_dir / 'delta_config.json'
    cfg = json.load(open(cfg_path)) if cfg_path.exists() else {}
    tau_C = cfg.get('tau_C')
    cfg.setdefault('internal_probes', {})
    if tau_C is not None:
        delta_max = 1.0 - min(tau_T, tau_V, tau_C)
        cfg['internal_probes']['d_cautious'] = round(delta_max / 3, 4)
        cfg['internal_probes']['d_restricted'] = round(delta_max * 2 / 3, 4)
    cfg['internal_probes'].update({'tau_T': round(tau_T, 4), 'tau_V': round(tau_V, 4), 'auc_T_cal': round(auc_T, 4), 'auc_V_cal': round(auc_V, 4), 'calibration_source_T': 'lmsys/toxic-chat', 'calibration_source_V': 'onullusoy/harmful-contents', 'clip_layer': CLIP_LAYER})
    json.dump(cfg, open(cfg_path, 'w'), indent=2)
    print(f"\n{'=' * 60}")
    print(f'  tau_T = {tau_T:.4f}  (AUC={auc_T:.4f}, on toxic-chat)')
    print(f'  tau_V = {tau_V:.4f}  (AUC={auc_V:.4f}, on HarmfulContents)')
    print(f"{'=' * 60}")
    print(f'\n  Updated: {cfg_path}')
if __name__ == '__main__':
    CONFIG = {'probes': 'probes/rebuilt_v13/', 'out': 'probes/rebuilt_v13/delta', 'gpu': 3, 'n_cal': 400, 'harmful_splits': 'probes/rebuilt_v13/delta/harmful_contents_reserved.json', 'recompute': True}
    in_jupyter = 'ipykernel' in sys.argv[0] if sys.argv else False
    if not in_jupyter:
        parser = argparse.ArgumentParser()
        parser.add_argument('--probes', default=CONFIG['probes'])
        parser.add_argument('--out', default=CONFIG['out'])
        parser.add_argument('--gpu', type=int, default=CONFIG['gpu'])
        parser.add_argument('--n_cal', type=int, default=CONFIG['n_cal'])
        parser.add_argument('--harmful_splits', default=CONFIG['harmful_splits'])
        parser.add_argument('--recompute', action='store_true')
        args = parser.parse_args()
    else:
        args = argparse.Namespace(**CONFIG)
    run(args)
